name: Linting

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Run frontend lint
        run: yarn run lint

      - name: Run tests
        run: yarn run test
